version: '2'

services:
  app:
    build:
      context: .
    links:
      - aws
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "tail -f /dev/null"

  aws:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=127.0.0.1
    ports:
      - 4566:4566
      - 4576:4576
