version: '2'

services:
  app:
    build:
      context: .
    links:
      - aws
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "tail -f /dev/null"

  aws:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=aws
